### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by chodson** [RossLab/Bradysia-GRCs#6]
- [x] remake BUSCO table with new L X A assignments (done in 4783d84)
- ~look into RNAseq stuff again.~
    - one thing we’ll need eventually is a table linking the transcripts pulled out of the annotation to the nodes they come from and also potentially to the busco id’s.
- ~annotation/expression:~
    - [x] number of genes annotated on each chromosome type
    - relative expression of genes on each chromosome type (log tpm histograms/violin plots)
    - expression of paralogs (L-AX) in germ and somatic tissues
    - make sure no expression of L in somatic cells
- all-vs-all blast transcripts
    - [x] to determine paralogs
    - [x] also to look for L divergence (i.e. assembly errors)
- [x] blobplot for spades assembly

- look into coverage levels of L genes (and possibly SNP's) to look for collapsed L haplotypes (and whether coverage levels overall suggest that there are two distinct L chromosomes
    - [x] determine cov levels of L genes (from bam files? or need to map to genes specifically)
    - [x] look to see if L-L paralogs fall into a region of half the cov as single L genes

- ~dN/dS to look at selection on L genes vs. A genes~
   - decide if to use BUSCO (more species) or other type of orthology (more genes)
   - run PAML

- **GRC restricted genes** (that don't have paralogs on A chromosomes or X).
    - [ ] how many are there? Determine how many L genes from blast results don't have a paralog or have a paralog on the L.
    - [ ] blast single copy L genes from BUSCO to the rest of the genome? (or somehow bull these busco genes out of all by all blast??
    - [ ] run BUSCO on John's assembly (and potentially somatic assembly) to see if the single L or L-L BUSCOs are found in these assemblies.

- **BUSCO phylogenies**
    - [x] filter BUSCO alignments based on some criteria (length of alignment for X number of species)
    - [x] re-run iqtree, rooting the trees with one of the outgroup species.
    - [ ] find a way to group phylogenies based on where the L gene falls. (https://github.com/mrmckain/PhyDS/)
